### ISSUE TITLE
Bundled JVMs

### ISSUE THREAD

**Issue by CLOVIS-AI** [rubo77/log4j_checker_beta#1]
If any app bundles the JVM in their own package, 'java' might not be installed but one such apps could still be vulnerable.

**Comment by rubo77** [comment]
Is there a way to check for those too then?

**Comment by CLOVIS-AI** [comment]
Each program will do it its own way. I'm not aware of a general solution.

**Comment by rubo77** [comment]
We scan inside  JAR/WAR/EAR files now.

Is there anything else we could do?

**Comment by CLOVIS-AI** [comment]
Looks good to me, I'm not aware of anything else that can be done.
