### ISSUE TITLE
CentOS 7, line 15, information, command not found.

### ISSUE THREAD

**Issue by craiglondon** [rubo77/log4j_checker_beta#14]
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

$ sudo wget https://raw.githubusercontent.com/rubo77/log4j_checker_beta/main/log4j_checker_beta.sh -q -O - |bash
bash: line 15: information: command not found

**Comment by stefan123t** [comment]
@rubo77 it uses information, warning, ok, etc. through-out the script
I would expect the logging function definitions in line 23-33 to be early in the beginning of the shell script.

**Comment by rubo77** [comment]
Fixed in
https://github.com/rubo77/log4j_checker_beta/commit/0f5a3df2b583dde82fa1e69d49511c79aa8ac834#diff-16c18e323971e496f558700372d7e8d1f113510b0759fccae18fd09567df6f0d

**Comment by craiglondon** [comment]
@rubo77 thanks!

**Comment by stefan123t** [comment]
Many thanks to rubo77.
