### ISSUE TITLE
MacOS, mktemp illegal option

### ISSUE THREAD

**Issue by craiglondon** [rubo77/log4j_checker_beta#22]
Getting an error when running the script on MacOS

$ wget https://raw.githubusercontent.com/rubo77/log4j_checker_beta/main/log4j_checker_beta.sh -q -O - |bash
[INFO] using default hash file. If you want to use other hashes, set another URL as first argument
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
--2021-12-30 12:00:52--  https://raw.githubusercontent.com/rubo77/log4j_checker_beta/main/hashes-pre-cve.txt

From the man page
`OPTIONS
     The available options are as follows:

     -d      Make a directory instead of a file.

     -q      Fail silently if an error occurs.  This is useful if a script does not want error output to go to standard error.

     -t prefix
             Generate a template (using the supplied prefix and TMPDIR if set) to create a filename template.

     -u      Operate in ``unsafe'' mode.  The temp file will be unlinked before mktemp exits.  This is slightly better than mktemp(3) but still introduces a race
             condition.  Use of this option is not encouraged.`

**Comment by rubo77** [comment]
Maybe the q and O must be in front of the URL?

**Comment by craiglondon** [comment]
Thanks!
